name: first

on: push

jobs:
	job1:
		name: First job
		runs-on: ubuntu-latest
		steps:
		- name: Step one
		# actions is the namespace that points to actions maintained by GitHub
		uses: actions/checkout@v2
		- name: Step two
		run: |
        echo "Code is now accessible."
        ls -la
	job2:
		name: Seconf job
		runs-on: windows-latest
		steps:
		- name: Step one
		uses: actions/checkout@v2
		- name: Step two
		run: |
        echo "Code is now accessible."
        dir